import { StyleSheet, Platform, StatusBar } from 'react-native';

export const estilosRegistrar = StyleSheet.create({
  areaSegura: {
    flex: 1,
    backgroundColor: '#F8F9FA',
  },
  contenedorScroll: {
    padding: 20,
    paddingBottom: 0,
  },
  encabezadoSuperior: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop:
      Platform.OS === 'android' ? (StatusBar.currentHeight || 20) + -18 : 1,
    marginBottom: 15,
  },
  migasPan: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  textoMigaInactivo: {
    color: '#A0AEC0',
    fontSize: 14,
  },
  textoMigaActivo: {
    color: '#1A202C',
    fontSize: 14,
    fontWeight: 'bold',
  },
  cabeceraPantalla: {
    paddingBottom: 20,
  },
  tituloPantalla: {
    fontSize: 24,
    fontWeight: '900',
    color: '#1A202C',
    marginBottom: 5,
  },
  subtituloPantalla: {
    fontSize: 14,
    color: '#718096',
  },
  tarjetaBlanca: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 20,
    paddingTop: 30,
    paddingBottom: 30,
    flex: 1,
  },
  etiquetaSuperior: {
    color: '#C8005B',
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 1,
    marginBottom: 10,
  },
  tituloPrincipal: {
    fontSize: 24,
    color: '#1A202C',
    marginBottom: 25,
  },
  contenedorTabs: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 30,
  },
  tabBoton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 15,
    borderRadius: 10,
    borderWidth: 1,
  },
  tabIngreso: {
    marginRight: 10,
  },
  tabEgreso: {
    marginLeft: 10,
  },
  tabInactivo: {
    backgroundColor: '#F8F9FA',
    borderColor: '#EDF2F7',
  },
  tabIngresoActivo: {
    backgroundColor: '#E6F4EA',
    borderColor: '#C6E5D0',
  },
  tabEgresoActivo: {
    backgroundColor: '#FFF0F5',
    borderColor: '#FBCFE8',
  },
  textoTabInactivo: {
    color: '#A0AEC0',
    fontSize: 14,
    fontWeight: 'bold',
    marginLeft: 8,
  },
  textoTabIngresoActivo: {
    color: '#1E8E3E',
    fontSize: 14,
    fontWeight: 'bold',
    marginLeft: 8,
  },
  textoTabEgresoActivo: {
    color: '#C8005B',
    fontSize: 14,
    fontWeight: 'bold',
    marginLeft: 8,
  },
  grupoInput: {
    marginBottom: 20,
    position: 'relative',
    zIndex: 1,
  },
  grupoInputZIndexAlto: {
    marginBottom: 20,
    position: 'relative',
    zIndex: 10,
  },
  labelInput: {
    fontSize: 12,
    color: '#718096',
    marginBottom: 8,
  },
  cajaInput: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#EDF2F7',
    borderRadius: 12,
    paddingHorizontal: 15,
    height: 55,
    backgroundColor: '#FFFFFF',
  },
  cajaInputActiva: {
    borderColor: '#FBCFE8',
  },
  simboloMoneda: {
    fontSize: 20,
    color: '#A0AEC0',
    marginRight: 10,
  },
  inputPrincipal: {
    flex: 1,
    fontSize: 24,
    color: '#1A202C',
  },
  inputTexto: {
    flex: 1,
    fontSize: 14,
    color: '#1A202C',
  },
  textoMoneda: {
    fontSize: 12,
    color: '#A0AEC0',
  },
  botonGuardar: {
    backgroundColor: '#C8005B',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 12,
    height: 55,
    marginTop: 20,
  },
  textoBotonGuardar: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
    marginLeft: 8,
  },
  dropdownContenedor: {
    position: 'absolute',
    top: 80,
    left: 0,
    right: 0,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#EDF2F7',
    borderRadius: 8,
    elevation: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  dropdownItem: {
    paddingVertical: 15,
    paddingHorizontal: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#F7FAFC',
  },
  dropdownItemActivo: {
    backgroundColor: '#0066CC',
  },
  dropdownItemTexto: {
    fontSize: 14,
    color: '#1A202C',
  },
  dropdownItemTextoActivo: {
    fontSize: 14,
    color: '#FFFFFF',
  },
  botonChatbotFlotante: {
    position: 'absolute',
    bottom: 20,
    right: 20,
    backgroundColor: '#FFF0F5',
    width: 60,
    height: 60,
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 6,
    shadowColor: '#C8005B',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    borderWidth: 1,
    borderColor: '#F3D2DF',
  },
  contenedorIconosCabecera: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  botonPerfilCabecera: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#C8005B',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 15,
  },
  textoPerfilCabecera: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 14,
  },
  modalFondo: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'flex-end',
  },
  modalContenedorUsuario: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
    paddingBottom: Platform.OS === 'ios' ? 40 : 24,
  },
  lineaArrastre: {
    width: 40,
    height: 4,
    backgroundColor: '#CBD5E0',
    borderRadius: 2,
    alignSelf: 'center',
    marginBottom: 20,
  },
  avatarGrande: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#C8005B',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    marginBottom: 15,
  },
  textoAvatarGrande: {
    fontSize: 28,
    fontWeight: '900',
    color: '#FFFFFF',
  },
  nombreUsuarioModal: {
    fontSize: 20,
    fontWeight: '900',
    color: '#1A202C',
    textAlign: 'center',
    marginBottom: 10,
  },
  badgeVerificado: {
    backgroundColor: '#E6F4EA',
    alignSelf: 'center',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 25,
  },
  textoBadgeVerificado: {
    color: '#1E8E3E',
    fontSize: 12,
    fontWeight: 'bold',
    marginLeft: 4,
  },
  filaDatoUsuario: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#EDF2F7',
  },
  etiquetaDato: {
    fontSize: 14,
    color: '#718096',
  },
  valorDato: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#1A202C',
  },
  botonCerrarSesion: {
    backgroundColor: '#E53E3E',
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 30,
  },
  textoBotonCerrarSesion: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  modalFondoCentro: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  tarjetaMeta: {
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 24,
    width: '100%',
    alignItems: 'center',
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
  },
  tituloMeta: {
    fontSize: 20,
    fontWeight: '900',
    color: '#1A202C',
    marginBottom: 8,
    textAlign: 'center',
  },
  subtituloMeta: {
    fontSize: 14,
    color: '#718096',
    textAlign: 'center',
    marginBottom: 20,
  },
  inputMetaContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#EDF2F7',
    borderRadius: 12,
    paddingHorizontal: 15,
    height: 55,
    width: '100%',
    marginBottom: 20,
    backgroundColor: '#F8F9FA',
  },
  textoMonedaMeta: {
    fontSize: 18,
    color: '#A0AEC0',
    marginRight: 10,
    fontWeight: 'bold',
  },
  inputMeta: {
    flex: 1,
    fontSize: 24,
    fontWeight: 'bold',
    color: '#1A202C',
  },
  botonGuardarMeta: {
    backgroundColor: '#C8005B',
    borderRadius: 12,
    width: '100%',
    height: 55,
    justifyContent: 'center',
    alignItems: 'center',
  },
  textoBotonMeta: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
});
