import { StyleSheet, Platform, StatusBar } from 'react-native';

export const estilosHistorial = StyleSheet.create({
  areaSegura: {
    flex: 1,
    backgroundColor: '#F8F9FA',
  },
  contenedorScroll: {
    padding: 20,
    paddingBottom: 100,
  },
  encabezadoSuperior: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: Platform.OS === 'android' ? (StatusBar.currentHeight || 20) + -18 : 1,
    marginBottom: 15,
  },
  migasPan: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  textoMigaInactivo: {
    color: '#A0AEC0',
    fontSize: 14,
  },
  textoMigaActivo: {
    color: '#1A202C',
    fontSize: 14,
    fontWeight: 'bold',
  },
  cabeceraPantalla: {
    marginBottom: 20,
  },
  tituloPantalla: {
    fontSize: 24,
    fontWeight: '900',
    color: '#1A202C',
    marginBottom: 5,
  },
  subtituloPantalla: {
    fontSize: 14,
    color: '#718096',
  },
  botonDescargar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#EDF2F7',
    borderRadius: 8,
    paddingHorizontal: 15,
    paddingVertical: 10,
    alignSelf: 'flex-start',
    marginBottom: 20,
  },
  textoBotonDescargar: {
    color: '#1A202C',
    fontSize: 14,
    fontWeight: '500',
    marginLeft: 8,
  },
  tarjetaPrincipal: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 20,
    borderWidth: 1,
    borderColor: '#EDF2F7',
  },
  contenedorTabs: {
    flexDirection: 'row',
    backgroundColor: '#F8F9FA',
    borderRadius: 10,
    padding: 4,
    marginBottom: 20,
  },
  tab: {
    flex: 1,
    paddingVertical: 10,
    alignItems: 'center',
    borderRadius: 8,
  },
  tabActivo: {
    backgroundColor: '#FFFFFF',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  textoTab: {
    fontSize: 14,
    color: '#718096',
    fontWeight: '500',
  },
  textoTabActivo: {
    color: '#C8005B',
    fontWeight: 'bold',
  },
  filaBuscador: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  cajaBuscador: {
    flex: 1.5,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#EDF2F7',
    borderRadius: 8,
    paddingHorizontal: 10,
    height: 45,
    marginRight: 10,
  },
  inputBuscador: {
    flex: 1,
    fontSize: 14,
    marginLeft: 8,
    color: '#1A202C',
  },
  cajaMes: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: '#EDF2F7',
    borderRadius: 8,
    paddingHorizontal: 10,
    height: 45,
  },
  textoMes: {
    fontSize: 14,
    color: '#718096',
  },
  encabezadoTabla: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: '#EDF2F7',
    paddingBottom: 10,
    marginBottom: 10,
  },
  textoEncabezado: {
    color: '#A0AEC0',
    fontSize: 12,
  },
  filaMovimiento: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F7FAFC',
  },
  ladoIzquierdo: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 2,
  },
  iconoContenedor: {
    width: 45,
    height: 45,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  textosIzquierda: {
    flex: 1,
  },
  tituloMovimiento: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#1A202C',
  },
  categoriaMovimiento: {
    fontSize: 12,
    color: '#A0AEC0',
    marginTop: 2,
  },
  centroMovimiento: {
    flex: 1,
    alignItems: 'center',
  },
  fechaTexto: {
    fontSize: 12,
    color: '#A0AEC0',
    textAlign: 'center',
  },
  ladoDerecho: {
    flex: 1.2,
    alignItems: 'flex-end',
  },
  montoTexto: {
    fontSize: 14,
    fontWeight: 'bold',
  },
  tipoTexto: {
    fontSize: 12,
    color: '#A0AEC0',
    marginTop: 2,
  },
  pieTarjeta: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 20,
    paddingTop: 15,
    borderTopWidth: 1,
    borderTopColor: '#EDF2F7',
  },
  textoPieFuerte: {
    fontSize: 12,
    color: '#718096',
    fontWeight: 'bold',
  },
  textoPieSuave: {
    fontSize: 12,
    color: '#A0AEC0',
  },
  botonChatbotFlotante: {
    position: 'absolute',
    bottom: 20,
    right: 20,
    backgroundColor: '#FFF0F5',
    width: 60,
    height: 60,
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 6,
    shadowColor: '#C8005B',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    borderWidth: 1,
    borderColor: '#F3D2DF',
  },
  contenedorIconosCabecera: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  botonPerfilCabecera: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#C8005B', 
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 15,
  },
  textoPerfilCabecera: {
    color: '#FFFFFF', 
    fontWeight: 'bold',
    fontSize: 14,
  },
  modalFondo: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'flex-end',
  },
  modalContenedorUsuario: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
    paddingBottom: Platform.OS === 'ios' ? 40 : 24,
  },
  lineaArrastre: {
    width: 40,
    height: 4,
    backgroundColor: '#CBD5E0',
    borderRadius: 2,
    alignSelf: 'center',
    marginBottom: 20,
  },
  avatarGrande: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#C8005B', 
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    marginBottom: 15,
  },
  textoAvatarGrande: {
    fontSize: 28,
    fontWeight: '900',
    color: '#FFFFFF',
  },
  nombreUsuarioModal: {
    fontSize: 20,
    fontWeight: '900',
    color: '#1A202C',
    textAlign: 'center',
    marginBottom: 10,
  },
  badgeVerificado: {
    backgroundColor: '#E6F4EA',
    alignSelf: 'center',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 25,
  },
  textoBadgeVerificado: {
    color: '#1E8E3E',
    fontSize: 12,
    fontWeight: 'bold',
    marginLeft: 4,
  },
  filaDatoUsuario: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#EDF2F7',
  },
  etiquetaDato: {
    fontSize: 14,
    color: '#718096',
  },
  valorDato: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#1A202C',
  },
  botonCerrarSesion: {
    backgroundColor: '#E53E3E',
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 30,
  },
  textoBotonCerrarSesion: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  }
});