import { StyleSheet, Platform, StatusBar } from 'react-native';

export const estilosBalance = StyleSheet.create({
  areaSegura: {
    flex: 1,
    backgroundColor: '#F8F9FA',
  },
  contenedorScroll: {
    padding: 20,
    paddingBottom: 30, 
  },
  encabezadoSuperior: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: Platform.OS === 'android' ? (StatusBar.currentHeight || 20) + -18 : 1,
    marginBottom: 15,
  },
  migasPan: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  textoMigaInactivo: {
    color: '#A0AEC0',
    fontSize: 14,
  },
  textoMigaActivo: {
    color: '#1A202C',
    fontSize: 14,
    fontWeight: 'bold',
  },
  contenedorIconosCabecera: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  botonPerfilCabecera: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#C8005B',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 15,
  },
  textoPerfilCabecera: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 14,
  },
  cabeceraPantalla: {
    marginBottom: 20,
  },
  tituloPantalla: {
    fontSize: 24,
    fontWeight: '900',
    color: '#1A202C',
    marginBottom: 5,
  },
  subtituloPantalla: {
    fontSize: 14,
    color: '#718096',
  },
  tarjetaBalance: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 20,
    borderWidth: 1,
    borderColor: '#EDF2F7',
    marginBottom: 20,
  },
  cabeceraSelector: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  tituloTarjeta: {
    fontSize: 16,
    fontWeight: '900',
    color: '#1A202C',
  },
  selectorMes: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#EDF2F7',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  textoMes: {
    fontSize: 12,
    color: '#718096',
    marginRight: 5,
  },
  contenedorGrafico: {
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 20,
  },
  anilloGrafico: {
    width: 180,
    height: 180,
    borderRadius: 90,
    borderWidth: 18,
    borderColor: '#C8005B',
    borderTopColor: '#FFB81C', 
    alignItems: 'center',
    justifyContent: 'center',
  },
  emojiGrafico: {
    fontSize: 36,
    marginBottom: 5,
  },
  textoEstadoGrafico: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#1A202C',
  },
  filaTarjetasPequeñas: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 10,
  },
  tarjetaPequeña: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 15,
    borderWidth: 1,
    borderColor: '#EDF2F7',
  },
  iconoPequeñoEntrada: {
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: '#E6F4EA',
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconoPequeñoSalida: {
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: '#FFF0F5',
    justifyContent: 'center',
    alignItems: 'center',
  },
  etiquetaPequeña: {
    fontSize: 12,
    color: '#718096',
    marginTop: 10,
  },
  montoPequeño: {
    fontSize: 18,
    fontWeight: '900',
    color: '#1A202C',
    marginVertical: 4,
  },
  subtextoPequeño: {
    fontSize: 10,
    color: '#A0AEC0',
  },
  tarjetaBalanceNeto: {
    backgroundColor: '#FFF9E6',
    borderRadius: 16,
    padding: 20,
    marginTop: 15,
  },
  etiquetaBalanceNeto: {
    fontSize: 14,
    color: '#A67C00',
  },
  filaMontoNeto: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 8,
  },
  montoNeto: {
    fontSize: 28,
    fontWeight: '900',
    color: '#1A202C',
    marginLeft: 8,
  },
  tituloPensado: {
    fontSize: 20,
    fontWeight: '900',
    color: '#1A202C',
    marginTop: 20,
  },
  subtituloPensado: {
    fontSize: 14,
    color: '#718096',
    marginBottom: 15,
  },
  tarjetaSugerencia: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 15,
    borderWidth: 1,
    borderColor: '#EDF2F7',
    marginBottom: 15,
  },
  filaSugerenciaCabecera: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  iconoSugerencia: {
    fontSize: 20,
    marginRight: 10,
  },
  tituloSugerencia: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#1A202C',
  },
  montoSugerencia: {
    fontSize: 18,
    fontWeight: '900',
    color: '#C8005B',
  },
  textoSugerencia: {
    fontSize: 12,
    color: '#718096',
    marginTop: 5,
  },
  filaListaSugerencia: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 10,
  },
  textoNota: {
    fontSize: 12,
    color: '#A0AEC0',
    textAlign: 'center',
    marginTop: 10,
    marginBottom: 0,
    fontWeight: '500',
  },
  botonChatbotFlotante: {
    position: 'absolute',
    bottom: 20,
    right: 20,
    backgroundColor: '#FFF0F5',
    width: 60,
    height: 60,
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 6,
    shadowColor: '#C8005B',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    borderWidth: 1,
    borderColor: '#F3D2DF',
  },
  modalFondo: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'flex-end',
  },
  modalContenedorUsuario: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
    paddingBottom: Platform.OS === 'ios' ? 40 : 24,
  },
  lineaArrastre: {
    width: 40,
    height: 4,
    backgroundColor: '#CBD5E0',
    borderRadius: 2,
    alignSelf: 'center',
    marginBottom: 20,
  },
  avatarGrande: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#C8005B',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    marginBottom: 15,
  },
  textoAvatarGrande: {
    fontSize: 28,
    fontWeight: '900',
    color: '#FFFFFF',
  },
  nombreUsuarioModal: {
    fontSize: 20,
    fontWeight: '900',
    color: '#1A202C',
    textAlign: 'center',
    marginBottom: 10,
  },
  badgeVerificado: {
    backgroundColor: '#E6F4EA',
    alignSelf: 'center',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 25,
  },
  textoBadgeVerificado: {
    color: '#1E8E3E',
    fontSize: 12,
    fontWeight: 'bold',
    marginLeft: 4,
  },
  filaDatoUsuario: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#EDF2F7',
  },
  etiquetaDato: {
    fontSize: 14,
    color: '#718096',
  },
  valorDato: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#1A202C',
  },
  botonCerrarSesion: {
    backgroundColor: '#E53E3E',
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 30,
  },
  textoBotonCerrarSesion: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  }
});