import { StyleSheet, Platform, StatusBar } from 'react-native';

export const estilos = StyleSheet.create({
  areaSegura: {
    flex: 1,
    backgroundColor: '#F8F9FA',
  },
  contenedorScroll: {
    padding: 20,
    paddingBottom: 0,
  },
  modalFondo: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalFondoPerfil: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'flex-end',
  },
  encabezadoSuperior: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop:
      Platform.OS === 'android' ? (StatusBar.currentHeight || 20) + -18 : 1,
    marginBottom: 15,
  },
  migasPan: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  textoMigaInactivo: {
    color: '#A0AEC0',
    fontSize: 14,
  },
  textoMigaActivo: {
    color: '#1A202C',
    fontSize: 14,
    fontWeight: 'bold',
  },
  iconoCampana: {},
  cabecera: {
    marginBottom: 20,
  },
  saludo: {
    fontSize: 28,
    fontWeight: '900',
    color: '#1A202C',
  },
  subtitulo: {
    fontSize: 14,
    color: '#718096',
    marginTop: 5,
  },
  tarjetaMagenta: {
    backgroundColor: '#C8005B',
    borderRadius: 20,
    paddingTop: 18,
    paddingBottom: 30,
    paddingHorizontal: 20,
    elevation: 5,
    shadowColor: '#C8005B',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    marginTop: 1,
  },
  filaSuperiorTarjeta: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 15,
  },
  contenedorEtiqueta: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  iconoCartera: {
    marginRight: 8,
  },
  textoEtiqueta: {
    color: '#FFFFFF',
    fontSize: 14,
    opacity: 0.9,
  },
  botonOjo: {
    padding: 5,
  },
  contenedorMonto: {
    flexDirection: 'row',
    alignItems: 'baseline',
    marginTop: -10,
    marginBottom: 5,
  },
  simboloMoneda: {
    color: '#FFFFFF',
    fontSize: 36,
    fontWeight: 'bold',
    marginRight: 5,
  },
  montoTotal: {
    color: '#FFFFFF',
    fontSize: 42,
    fontWeight: '900',
    letterSpacing: -1,
    flexShrink: 1,
  },
  montoOculto: {
    fontSize: 28,
    letterSpacing: 3,
  },
  textoMoneda: {
    color: '#FFFFFF',
    fontSize: 14,
    marginLeft: 8,
    opacity: 0.8,
  },
  textoInformativo: {
    color: '#FFFFFF',
    fontSize: 12,
    opacity: 0.8,
    marginTop: 5,
    marginBottom: 20,
  },
  filaBotones: {
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  botonSecundario: {
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    paddingVertical: 12,
    paddingHorizontal: 15,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  botonPrimario: {
    backgroundColor: '#FFFFFF',
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 10,
  },
  textoBotonSecundario: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: 'bold',
  },
  textoBotonPrimario: {
    color: '#C8005B',
    fontSize: 12,
    fontWeight: 'bold',
  },
  botonChatbotFlotante: {
    position: 'absolute',
    bottom: 20,
    right: 20,
    backgroundColor: '#FFF0F5',
    width: 60,
    height: 60,
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 6,
    shadowColor: '#C8005B',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    borderWidth: 1,
    borderColor: '#F3D2DF',
  },
  tarjetaDorada: {
    backgroundColor: '#FFF9E6',
    borderRadius: 20,
    padding: 20,
    marginTop: 20,
    position: 'relative',
    overflow: 'hidden',
  },
  filaEtiquetaDorada: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
  },
  textoEtiquetaDorada: {
    color: '#A67C00',
    fontSize: 12,
    fontWeight: 'bold',
    letterSpacing: 1,
    marginLeft: 5,
  },
  tituloDorado: {
    color: '#1A202C',
    fontSize: 22,
    fontWeight: '900',
    lineHeight: 28,
    marginBottom: 10,
    maxWidth: '85%',
  },
  subtituloDorado: {
    color: '#718096',
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 20,
    maxWidth: '80%',
  },
  botonDescubre: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  textoBotonDescubre: {
    color: '#A67C00',
    fontSize: 14,
    fontWeight: 'bold',
    marginRight: 8,
  },
  iconoEstrellaDecorativa: {
    position: 'absolute',
    right: -3,
    top: '30%',
    opacity: 0.4,
  },
  seccionCuentas: {
    marginTop: 30,
  },
  encabezadoSeccion: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 5,
    marginLeft: 8,
  },
  tituloSeccion: {
    fontSize: 20,
    fontWeight: '900',
    color: '#1A202C',
  },
  badgeCuentas: {
    backgroundColor: '#EDF2F7',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 2,
    marginLeft: 10,
  },
  textoBadge: {
    color: '#718096',
    fontSize: 12,
    fontWeight: 'bold',
  },
  subtituloSeccion: {
    fontSize: 14,
    color: '#718096',
    marginBottom: 15,
    marginLeft: 8,
  },
  tarjetaCuenta: {
    backgroundColor: '#FFFFFF',
    borderRadius: 15,
    padding: 15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#EDF2F7',
  },
  ladoIzquierdoCuenta: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  iconoCuentaContenedor: {
    width: 45,
    height: 45,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 15,
  },
  tituloCuenta: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#1A202C',
  },
  subtituloCuenta: {
    fontSize: 12,
    color: '#A0AEC0',
    marginTop: 2,
  },
  ladoDerechoCuenta: {
    alignItems: 'flex-end',
  },
  saldoCuenta: {
    fontSize: 18,
    fontWeight: '900',
    color: '#1A202C',
  },
  monedaCuenta: {
    fontSize: 10,
    color: '#A0AEC0',
    marginTop: 2,
  },
  modalContenedor: {
    width: '90%',
    maxHeight: '85%',
    backgroundColor: '#FFFFFF',
    borderRadius: 24,
    padding: 20,
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
  },
  modalCabecera: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 3,
  },
  textoModalEtiqueta: {
    color: '#C8005B',
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 1,
  },
  botonCerrarModal: {
    padding: 5,
  },
  modalTituloCuenta: {
    fontSize: 28,
    color: '#1A202C',
    marginBottom: 10,
  },
  modalSaldoGrande: {
    fontSize: 42,
    fontWeight: '900',
    color: '#C8005B',
    marginBottom: 30,
  },
  modalEncabezadoTabla: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: '#EDF2F7',
    paddingBottom: 10,
    marginBottom: 20,
  },
  modalTextoTabla: {
    color: '#A0AEC0',
    fontSize: 12,
  },
  listaMovimientosCuenta: {
    flexShrink: 1,
    width: '100%',
  },
  filaMovimientoCuenta: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#EDF2F7',
  },
  columnaMovimientoCuenta: { flex: 1.6, minWidth: 0, paddingRight: 8 },
  columnaFechaCuenta: { flex: 1, minWidth: 0, paddingHorizontal: 4 },
  columnaMontoCuenta: { flex: 1.4, minWidth: 0, paddingLeft: 4 },
  tituloMovimientoCuenta: { fontSize: 14, fontWeight: '600', color: '#1A202C' },
  detalleMovimientoCuenta: { fontSize: 12, color: '#718096', marginTop: 3 },
  fechaMovimientoCuenta: { textAlign: 'center' },
  montoMovimientoCuenta: { textAlign: 'right' },
  estadoVacioContenedor: {
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 40,
  },
  textoVacioTitulo: {
    fontSize: 16,
    color: '#4A5568',
    marginTop: 15,
    marginBottom: 5,
  },
  textoVacioSubtitulo: {
    fontSize: 14,
    color: '#A0AEC0',
  },
  contenedorBotonFijo: {
    marginTop: 10,
  },
  botonPrimarioGrande: {
    backgroundColor: '#C8005B',
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: 'center',
  },
  textoBotonPrimarioGrande: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  tarjetaMovimientos: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 20,
    marginTop: 30,
    borderWidth: 1,
    borderColor: '#EDF2F7',
  },
  cabeceraMovimientosSuperior: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 5,
  },
  tituloMovimientos: {
    fontSize: 20,
    fontWeight: '900',
    color: '#1A202C',
  },
  botonVerTodos: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  textoVerTodos: {
    color: '#C8005B',
    fontSize: 14,
    fontWeight: 'bold',
    marginRight: 5,
  },
  subtituloMovimientos: {
    fontSize: 14,
    color: '#718096',
    marginBottom: 20,
  },
  encabezadoTablaMov: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: '#EDF2F7',
    paddingBottom: 10,
    marginBottom: 10,
  },
  textoEncabezadoMov: {
    color: '#A0AEC0',
    fontSize: 12,
  },
  filaMovimiento: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F7FAFC',
  },
  ladoIzquierdoMov: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 2,
  },
  iconoMovContenedor: {
    width: 45,
    height: 45,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  textosIzquierdaMov: {
    flex: 1,
  },
  tituloMov: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#1A202C',
  },
  categoriaMov: {
    fontSize: 12,
    color: '#A0AEC0',
    marginTop: 2,
  },
  centroMov: {
    flex: 1,
    alignItems: 'center',
  },
  fechaMov: {
    fontSize: 12,
    color: '#A0AEC0',
    textAlign: 'center',
  },
  ladoDerechoMov: {
    flex: 1.2,
    alignItems: 'flex-end',
  },
  montoMov: {
    fontSize: 14,
    fontWeight: 'bold',
  },
  tipoMov: {
    fontSize: 12,
    color: '#A0AEC0',
    marginTop: 2,
  },
  pieMovimientos: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 15,
    paddingTop: 15,
    borderTopWidth: 1,
    borderTopColor: '#EDF2F7',
  },
  pieIzquierdaMov: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  puntoVerde: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#1E8E3E',
    marginRight: 8,
  },
  textoPieVerde: {
    fontSize: 12,
    color: '#718096',
  },
  textoPieGris: {
    fontSize: 12,
    color: '#A0AEC0',
  },
  tarjetaBalance: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 20,
    marginTop: 30,
    borderWidth: 1,
    borderColor: '#EDF2F7',
  },
  cabeceraBalance: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  tituloBalance: {
    fontSize: 18,
    fontWeight: '900',
    color: '#1A202C',
  },
  selectorMes: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  textoMes: {
    fontSize: 12,
    fontWeight: '500',
    color: '#718096',
    marginRight: 2,
  },
  contenedorGrafico: {
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 20,
  },
  anilloGrafico: {
    width: 160,
    height: 160,
    borderRadius: 80,
    borderWidth: 16,
    borderColor: '#C8005B',
    borderTopColor: '#FFB81C',
    alignItems: 'center',
    justifyContent: 'center',
  },
  emojiGrafico: {
    fontSize: 32,
    marginBottom: 5,
  },
  textoEstadoGrafico: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#1A202C',
  },
  contenedorLeyendas: {
    marginTop: 10,
    paddingHorizontal: 10,
  },
  filaLeyenda: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  itemLeyenda: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  puntoLeyenda: {
    width: 8,
    height: 8,
    borderRadius: 4,
    marginRight: 8,
  },
  textoLeyenda: {
    fontSize: 14,
    color: '#718096',
  },
  montoLeyenda: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#1A202C',
  },
  alertaVerde: {
    backgroundColor: '#E6F4EA',
    borderRadius: 8,
    paddingVertical: 10,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 15,
    marginBottom: 20,
  },
  textoAlertaVerde: {
    color: '#1E8E3E',
    fontSize: 14,
    fontWeight: 'bold',
  },
  botonSaludFinanciera: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 10,
  },
  textoBotonSalud: {
    color: '#C8005B',
    fontSize: 14,
    fontWeight: 'bold',
    marginRight: 8,
  },
  tarjetaFrase: {
    borderWidth: 1,
    borderColor: '#D6BCFA',
    borderStyle: 'dashed',
    borderRadius: 12,
    padding: 15,
    marginTop: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#FAF5FF',
  },
  textoFrase: {
    flex: 1,
    fontSize: 12,
    color: '#9F7AEA',
    textAlign: 'center',
    paddingHorizontal: 10,
  },
  piePantalla: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 20,
    marginBottom: 40,
  },
  textoPieDemo: {
    fontSize: 10,
    color: '#A0AEC0',
    marginLeft: 5,
  },
  contenedorIconosCabecera: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  botonPerfilCabecera: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: '#C8005B',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 15,
  },
  textoPerfilCabecera: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    fontSize: 14,
  },

  modalContenedorUsuario: {
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 24,
    paddingBottom: Platform.OS === 'ios' ? 40 : 24,
  },
  lineaArrastre: {
    width: 40,
    height: 4,
    backgroundColor: '#CBD5E0',
    borderRadius: 2,
    alignSelf: 'center',
    marginBottom: 20,
  },
  avatarGrande: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: '#C8005B',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    marginBottom: 15,
  },
  textoAvatarGrande: {
    fontSize: 28,
    fontWeight: '900',
    color: '#FFFFFF',
  },
  nombreUsuarioModal: {
    fontSize: 20,
    fontWeight: '900',
    color: '#1A202C',
    textAlign: 'center',
    marginBottom: 10,
  },
  badgeVerificado: {
    backgroundColor: '#E6F4EA',
    alignSelf: 'center',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 25,
  },
  textoBadgeVerificado: {
    color: '#1E8E3E',
    fontSize: 12,
    fontWeight: 'bold',
    marginLeft: 4,
  },
  filaDatoUsuario: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#EDF2F7',
  },
  etiquetaDato: {
    fontSize: 14,
    color: '#718096',
  },
  valorDato: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#1A202C',
  },
  botonCerrarSesion: {
    backgroundColor: '#E53E3E',
    paddingVertical: 16,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: 30,
  },
  textoBotonCerrarSesion: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
});
